version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis
    expose:
      - 6379
  twitter:
    image: 'vu/twitter:v0'
    ports:
      - '3000:3000'
    links: 
      - redis